"""add processing_task_id

Revision ID: 1ddb3d7b7e53
Revises: 9bfdbc8e8621
Create Date: 2026-09-06 22:07:33.214817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddb3d7b7e53'
down_revision: Union[str, Sequence[str], None] = '9bfdbc8e8621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('processing_task_id', sa.String(length=155), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'processing_task_id')
    # ### end Alembic commands ###
