"""add processing_started_at to files

Revision ID: 9bfdbc8e8621
Revises: d60ad7188e79
Create Date: 2026-09-06 21:32:13.385459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bfdbc8e8621'
down_revision: Union[str, Sequence[str], None] = 'd60ad7188e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'processing_started_at')
    # ### end Alembic commands ###
